# Generated by Django 5.1 on 2024-09-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(max_length=50)),
                ('contact', models.BigIntegerField()),
                ('objectif', models.TextField()),
                ('tech_skills', models.TextField()),
                ('exp_pro', models.TextField()),
                ('projets', models.TextField()),
                ('soft_skills', models.TextField()),
                ('education', models.TextField()),
                ('langue', models.CharField(max_length=150)),
                ('date_ajout', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
