# Generated by Django 5.2.7 on 2025-10-22 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.URLField(default='', unique=True)),
                ('github', models.URLField(default='', unique=True)),
                ('contact', models.BigIntegerField()),
                ('objectif', models.TextField()),
                ('ecole_1', models.CharField(max_length=255)),
                ('diplome_1', models.CharField(default='BACCALAUREAT', max_length=255)),
                ('date_debut_1', models.IntegerField(default=0)),
                ('date_fin_1', models.IntegerField(default=0)),
                ('ecole_2', models.CharField(blank=True, default='', max_length=255)),
                ('diplome_2', models.CharField(blank=True, default='', max_length=255)),
                ('date_debut_2', models.IntegerField(default=0)),
                ('date_fin_2', models.IntegerField(default=0)),
                ('langage_pro', models.CharField(default='', max_length=255)),
                ('frameworks', models.CharField(default='', max_length=255)),
                ('base_donnees', models.CharField(default='', max_length=255)),
                ('soft_skills', models.CharField(default='', max_length=255)),
                ('poste_1', models.CharField(default='', max_length=255)),
                ('entreprise_1', models.CharField(default='', max_length=255)),
                ('date_debut_poste_1', models.IntegerField(default=0)),
                ('date_fin_poste_1', models.IntegerField(default=0)),
                ('projet_1', models.CharField(default='', max_length=255)),
                ('lien_1', models.URLField(blank=True, default='', unique=True)),
                ('description_1', models.CharField(default=' ', max_length=500)),
                ('auteur', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
